# Setup
title:               PERSISMO
tagline:
description:
url: ''    # the base hostname & protocol for your site
baseurl: ''                  # the subpath of your site, e.g. /blog
permalink:           pretty

# About/contact
author:
  name:              PERSISMO
  twitter:           persismo
  github:            persismo

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Markdown processors
kramdown:
  toc_levels: 1..6
  auto_ids:     true
  footnote_nr:  1
  input: GFM
  entity_output: as_char
  hard_wrap: false