backend:
  name: github
  repo: persismo/website
  branch: main
  site_domain: persismo.netlify.com
publish_mode: editorial_workflow  
media_library:
  name: cloudinary
  config:
    cloud_name: persismo
    api_key: 262715164179826
    default_transformations:
      - - fetch_format: auto
          width: 800
          quality: auto
          crop: scale
collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Math", name: "math", widget: "boolean", default: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Hide", name: "hide", widget: "boolean", default: false}
      - label: 'Images'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''
        media_library:
          config:
            default_transformations:
              - fetch_format: auto
                width: 800    
                quality: auto
                crop: scale
      - {label: "Body", name: "body", widget: "markdown"}
